export const Rooms = [
  {
    id: 1,
    name: "Chambre Confortable & Lumineuse",
    location: "Campus A, Dschang",
    image: "https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg",
    isAvailable: true,
    isCertified: true,
    type: "Chambre simple",
    capacity: "1 place",
    surface: "15 m²",
    price: 25000,
    currency: "XAF",
    walkTime: "5 min",
    carTime: "2 min",
    features: [
      "Lit",
      "Bureau + chaise",
      "Armoire",
      "Salle de bain privée",
      "Eau chaude",
      "WiFi haut débit",
    ],
    contactPhone: "695056161",
    contactEmail: "contact.campusA@example.com",
  },
  {
    id: 2,
    name: "Studio Moderne en Centre-ville",
    location: "Centre-ville, Dschang",
    image: "https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg",
    isAvailable: true,
    isCertified: true,
    type: "Studio",
    capacity: "1 place",
    surface: "25 m²",
    price: 45000,
    currency: "XAF",
    walkTime: "10 min",
    carTime: "5 min",
    features: [
      "Lit double",
      "Cuisine équipée",
      "Salle de bain privée",
      "Télévision",
      "Climatisation",
      "Balcon",
    ],
    contactPhone: "695056162",
    contactEmail: "contact.centreville@example.com",
  },
  {
    id: 3,
    name: "Chambre Économique près de l'IUT",
    location: "IUT, Dschang",
    image: "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg",
    isAvailable: true,
    isCertified: false,
    type: "Chambre simple",
    capacity: "1 place",
    surface: "12 m²",
    price: 18000,
    currency: "XAF",
    walkTime: "3 min",
    carTime: "1 min",
    features: [
      "Lit simple",
      "Bureau",
      "Placard",
      "Cuisine partagée",
      "Douche partagée",
    ],
    contactPhone: "695056163",
    contactEmail: "contact.iut@example.com",
  },
  {
    id: 4,
    name: "Appartement F2 avec vue sur le Lac",
    location: "Lac Municipal, Dschang",
    image: "https://images.pexels.com/photos/261181/pexels-photo-261181.jpeg",
    isAvailable: true,
    isCertified: true,
    type: "Appartement F2",
    capacity: "2 places",
    surface: "40 m²",
    price: 60000,
    currency: "XAF",
    walkTime: "15 min",
    carTime: "7 min",
    features: [
      "2 Lits",
      "Cuisine équipée",
      "Salon meublé",
      "Vue panoramique",
      "Parking sécurisé",
      "WiFi",
    ],
    contactPhone: "695056164",
    contactEmail: "contact.lac@example.com",
  },
  {
    id: 5,
    name: "Chambre en colocation - Cité U",
    location: "Campus B, Dschang",
    image: "https://images.pexels.com/photos/2874254/pexels-photo-2874254.jpeg",
    isAvailable: false,
    isCertified: false,
    type: "Chambre en colocation",
    capacity: "1 place",
    surface: "10 m²",
    price: 12000,
    currency: "XAF",
    walkTime: "2 min",
    carTime: "1 min",
    features: [
      "Lit",
      "Bureau",
      "Cuisine commune",
      "Salle de bain partagée",
      "Jardin",
      "Réfrigérateur partagé",
    ],
    contactPhone: "695056165",
    contactEmail: "contact.campusB@example.com",
  },
  {
    id: 6,
    name: "Chambre spacieuse à Foutsa",
    location: "Foutsa, Dschang",
    image: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg",
    isAvailable: true,
    isCertified: true,
    type: "Chambre double",
    capacity: "2 places",
    surface: "20 m²",
    price: 35000,
    currency: "XAF",
    walkTime: "8 min",
    carTime: "4 min",
    features: [
      "Lit double",
      "Bureau + chaise",
      "Salle de bain privée",
      "Placard",
      "WiFi",
      "Accès terrasse",
    ],
    contactPhone: "695056166",
    contactEmail: "contact.foutsa@example.com",
  },
  {
    id: 7,
    name: "Studio compact - Campus B",
    location: "Campus B, Dschang",
    image: "https://images.pexels.com/photos/2034335/pexels-photo-2034335.jpeg",
    isAvailable: true,
    isCertified: true,
    type: "Studio",
    capacity: "1 place",
    surface: "22 m²",
    price: 30000,
    currency: "XAF",
    walkTime: "6 min",
    carTime: "3 min",
    features: [
      "Lit",
      "Cuisine intégrée",
      "Douche privée",
      "Climatisation",
      "Internet",
    ],
    contactPhone: "695056167",
    contactEmail: "contact.studio@example.com",
  },
  {
    id: 8,
    name: "Chambre avec lit à baldaquin",
    location: "M'mouck, Dschang",
    image: "https://images.pexels.com/photos/276583/pexels-photo-276583.jpeg",
    isAvailable: true,
    isCertified: true,
    type: "Chambre simple",
    capacity: "1 place",
    surface: "18 m²",
    price: 22000,
    currency: "XAF",
    walkTime: "12 min",
    carTime: "6 min",
    features: [
      "Lit à baldaquin",
      "Placard",
      "Bureau",
      "Salle de bain partagée",
      "Jardin",
    ],
    contactPhone: "695056168",
    contactEmail: "contact.mmouck@example.com",
  },
  {
    id: 9,
    name: "Appartement de luxe F3",
    location: "Route de l'Hôpital, Dschang",
    image: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg",
    isAvailable: false,
    isCertified: true,
    type: "Appartement F3",
    capacity: "3 places",
    surface: "85 m²",
    price: 85000,
    currency: "XAF",
    walkTime: "20 min",
    carTime: "10 min",
    features: [
      "3 chambres",
      "Cuisine moderne",
      "2 salles de bain",
      "Parking souterrain",
      "Sécurité 24h/24",
      "Balcon",
    ],
    contactPhone: "695056169",
    contactEmail: "contact.luxe@example.com",
  },
  {
    id: 10,
    name: "Chambre simple - Quartier Savane",
    location: "Savane, Dschang",
    image: "https://images.pexels.com/photos/2635038/pexels-photo-2635038.jpeg",
    isAvailable: true,
    isCertified: false,
    type: "Chambre simple",
    capacity: "1 place",
    surface: "14 m²",
    price: 15000,
    currency: "XAF",
    walkTime: "18 min",
    carTime: "9 min",
    features: ["Lit", "Bureau", "Armoire", "Cuisine partagée", "Cour arrière"],
    contactPhone: "695056170",
    contactEmail: "contact.savane@example.com",
  },
  {
    id: 11,
    name: "Studio avec vue sur la ville",
    location: "Centre-ville, Dschang",
    image: "https://images.pexels.com/photos/1329711/pexels-photo-1329711.jpeg",
    isAvailable: true,
    isCertified: true,
    type: "Studio",
    capacity: "1 place",
    surface: "30 m²",
    price: 50000,
    currency: "XAF",
    walkTime: "7 min",
    carTime: "4 min",
    features: [
      "Lit",
      "Cuisine équipée",
      "Salle de bain privée",
      "WiFi",
      "Climatisation",
      "Vue sur la ville",
    ],
    contactPhone: "695056171",
    contactEmail: "contact.vueville@example.com",
  },
  {
    id: 12,
    name: "Chambre spacieuse pour couple",
    location: "Campus A, Dschang",
    image: "https://images.pexels.com/photos/2082087/pexels-photo-2082087.jpeg",
    isAvailable: true,
    isCertified: true,
    type: "Chambre double",
    capacity: "2 places",
    surface: "25 m²",
    price: 38000,
    currency: "XAF",
    walkTime: "5 min",
    carTime: "2 min",
    features: [
      "Lit double",
      "Armoire",
      "Salle de bain privée",
      "WiFi",
      "Balcon",
    ],
    contactPhone: "695056172",
    contactEmail: "contact.couple@example.com",
  },
  {
    id: 13,
    name: "Appartement F4 familial",
    location: "Foutsa, Dschang",
    image: "https://images.pexels.com/photos/1370295/pexels-photo-1370295.jpeg",
    isAvailable: false,
    isCertified: true,
    type: "Appartement F4",
    capacity: "4 places",
    surface: "95 m²",
    price: 100000,
    currency: "XAF",
    walkTime: "10 min",
    carTime: "5 min",
    features: [
      "4 chambres",
      "Cuisine équipée",
      "2 salles de bain",
      "Grand salon",
      "Jardin privé",
    ],
    contactPhone: "695056173",
    contactEmail: "contact.familial@example.com",
  },
  {
    id: 14,
    name: "Chambre simple à M'mouck",
    location: "M'mouck, Dschang",
    image: "https://images.pexels.com/photos/2874404/pexels-photo-2874404.jpeg",
    isAvailable: true,
    isCertified: false,
    type: "Chambre simple",
    capacity: "1 place",
    surface: "16 m²",
    price: 17000,
    currency: "XAF",
    walkTime: "8 min",
    carTime: "4 min",
    features: [
      "Lit",
      "Bureau",
      "Placard",
      "Cuisine partagée",
      "Proche des commerces",
    ],
    contactPhone: "695056174",
    contactEmail: "contact.mmouck2@example.com",
  },
  {
    id: 15,
    name: "Studio Moderne avec terrasse",
    location: "Route de l'Hôpital, Dschang",
    image: "https://images.pexels.com/photos/1579782/pexels-photo-1579782.jpeg",
    isAvailable: true,
    isCertified: true,
    type: "Studio",
    capacity: "1 place",
    surface: "32 m²",
    price: 40000,
    currency: "XAF",
    walkTime: "12 min",
    carTime: "6 min",
    features: [
      "Lit",
      "Cuisine équipée",
      "Salle de bain privée",
      "Terrasse",
      "WiFi",
      "Sécurité 24/7",
    ],
    contactPhone: "695056175",
    contactEmail: "contact.terrasse@example.com",
  },
  {
    id: 16,
    name: "Chambre en résidence universitaire",
    location: "Campus B, Dschang",
    image:
      "https://images.pexels.com/photos/16654824/pexels-photo-16654824/free-photo-of-empty-bunk-bed-and-desk-in-hostel-room.jpeg",
    isAvailable: true,
    isCertified: false,
    type: "Chambre en colocation",
    capacity: "1 place",
    surface: "10 m²",
    price: 10000,
    currency: "XAF",
    walkTime: "1 min",
    carTime: "0 min",
    features: [
      "Lit superposé",
      "Bureau partagé",
      "Salle de bain commune",
      "Cuisine commune",
      "Salle d'étude",
    ],
    contactPhone: "695056176",
    contactEmail: "contact.residence@example.com",
  },
  {
    id: 17,
    name: "Appartement cosy près de l'IUT",
    location: "IUT, Dschang",
    image: "https://images.pexels.com/photos/2205565/pexels-photo-2205565.jpeg",
    isAvailable: true,
    isCertified: true,
    type: "Appartement F1",
    capacity: "1 place",
    surface: "28 m²",
    price: 30000,
    currency: "XAF",
    walkTime: "4 min",
    carTime: "2 min",
    features: [
      "Lit",
      "Cuisine kitchenette",
      "Douche privée",
      "Mobilier moderne",
      "Calme",
    ],
    contactPhone: "695056177",
    contactEmail: "contact.cosy@example.com",
  },
  {
    id: 18,
    name: "Chambre de style loft",
    location: "Centre-ville, Dschang",
    image: "https://images.pexels.com/photos/1699923/pexels-photo-1699923.jpeg",
    isAvailable: false,
    isCertified: true,
    type: "Chambre simple",
    capacity: "1 place",
    surface: "40 m²",
    price: 28000,
    currency: "XAF",
    walkTime: "15 min",
    carTime: "8 min",
    features: [
      "Lit surélevé",
      "Espace de travail",
      "Salle de bain privée",
      "WiFi",
      "Décoration moderne",
    ],
    contactPhone: "695056178",
    contactEmail: "contact.loft@example.com",
  },
  {
    id: 19,
    name: "Maison meublée",
    location: "Savane, Dschang",
    image: "https://images.pexels.com/photos/259972/pexels-photo-259972.jpeg",
    isAvailable: true,
    isCertified: true,
    type: "Maison",
    capacity: "5 places",
    surface: "150 m²",
    price: 150000,
    currency: "XAF",
    walkTime: "25 min",
    carTime: "12 min",
    features: [
      "3 chambres",
      "Salon complet",
      "Cuisine équipée",
      "2 salles de bain",
      "Terrasse",
      "Jardin",
    ],
    contactPhone: "695056179",
    contactEmail: "contact.maison@example.com",
  },
  {
    id: 20,
    name: "Chambre avec accès piscine",
    location: "M'mouck, Dschang",
    image: "https://images.pexels.com/photos/206172/pexels-photo-206172.jpeg",
    isAvailable: true,
    isCertified: false,
    type: "Chambre double",
    capacity: "2 places",
    surface: "35 m²",
    price: 55000,
    currency: "XAF",
    walkTime: "6 min",
    carTime: "3 min",
    features: [
      "Lit double",
      "Salle de bain privée",
      "Accès piscine",
      "WiFi",
      "Calme",
    ],
    contactPhone: "695056180",
    contactEmail: "contact.piscine@example.com",
  },
];


// Données de profil simulées
export const mockProfileData = {
    firstName: "Merveille",
    lastName: "Belinga Ntsama",
    email: "raymond2belinga@gmail.com",
    phone: "06 12 34 56 78",
    birthDate: "2002-03-15",
    university: "Sorbonne Université",
    city: "Paris",
    favorites: 12,
    searches: 45,
};