export const Rooms = [
  {
    id: 1,
    name: "Chambre Confortable & Lumineuse",
    location: "Campus A, Dschang",
    image: "https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg",
    isAvailable: true,
    isCertified: true,
    type: "Chambre simple",
    capacity: "1 place",
    price: 25000,
    currency: "XAF",
    features: [
      "Lit",
      "Bureau + chaise",
      "Armoire",
      "Salle de bain privée",
      "Eau chaude",
      "WiFi haut débit",
    ],
  },
  {
    id: 2,
    name: "Studio Moderne en Centre-ville",
    location: "Centre-ville, Dschang",
    image: "https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg",
    isAvailable: true,
    isCertified: true,
    type: "Studio",
    capacity: "1 place",
    price: 45000,
    currency: "XAF",
    features: [
      "Lit double",
      "Cuisine équipée",
      "Salle de bain privée",
      "Télévision",
      "Climatisation",
      "Balcon",
    ],
  },
  {
    id: 3,
    name: "Chambre Économique près de l'IUT",
    location: "IUT, Dschang",
    image: "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg",
    isAvailable: true,
    isCertified: false,
    type: "Chambre simple",
    capacity: "1 place",
    price: 18000,
    currency: "XAF",
    features: [
      "Lit simple",
      "Bureau",
      "Placard",
      "Cuisine partagée",
      "Douche partagée",
    ],
  },
  {
    id: 4,
    name: "Appartement F2 avec vue sur le Lac",
    location: "Lac Municipal, Dschang",
    image: "https://images.pexels.com/photos/261181/pexels-photo-261181.jpeg",
    isAvailable: true,
    isCertified: true,
    type: "Appartement F2",
    capacity: "2 places",
    price: 60000,
    currency: "XAF",
    features: [
      "2 Lits",
      "Cuisine équipée",
      "Salon meublé",
      "Vue panoramique",
      "Parking sécurisé",
      "WiFi",
    ],
  },
  {
    id: 5,
    name: "Chambre en colocation - Cité U",
    location: "Campus B, Dschang",
    image: "https://images.pexels.com/photos/2874254/pexels-photo-2874254.jpeg",
    isAvailable: false,
    isCertified: false,
    type: "Chambre en colocation",
    capacity: "1 place",
    price: 12000,
    currency: "XAF",
    features: [
      "Lit",
      "Bureau",
      "Cuisine commune",
      "Salle de bain partagée",
      "Jardin",
      "Réfrigérateur partagé",
    ],
  },
  {
    id: 6,
    name: "Chambre spacieuse à Foutsa",
    location: "Foutsa, Dschang",
    image: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg",
    isAvailable: true,
    isCertified: true,
    type: "Chambre double",
    capacity: "2 places",
    price: 35000,
    currency: "XAF",
    features: [
      "Lit double",
      "Bureau + chaise",
      "Salle de bain privée",
      "Placard",
      "WiFi",
      "Accès terrasse",
    ],
  },
  {
    id: 7,
    name: "Studio compact - Campus B",
    location: "Campus B, Dschang",
    image: "https://images.pexels.com/photos/2034335/pexels-photo-2034335.jpeg",
    isAvailable: true,
    isCertified: true,
    type: "Studio",
    capacity: "1 place",
    price: 30000,
    currency: "XAF",
    features: [
      "Lit",
      "Cuisine intégrée",
      "Douche privée",
      "Climatisation",
      "Internet",
    ],
  },
  {
    id: 8,
    name: "Chambre avec lit à baldaquin",
    location: "M'mouck, Dschang",
    image: "https://images.pexels.com/photos/276583/pexels-photo-276583.jpeg",
    isAvailable: true,
    isCertified: true,
    type: "Chambre simple",
    capacity: "1 place",
    price: 22000,
    currency: "XAF",
    features: [
      "Lit à baldaquin",
      "Placard",
      "Bureau",
      "Salle de bain partagée",
      "Jardin",
    ],
  },
  {
    id: 9,
    name: "Appartement de luxe F3",
    location: "Route de l'Hôpital, Dschang",
    image: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg",
    isAvailable: false,
    isCertified: true,
    type: "Appartement F3",
    capacity: "3 places",
    price: 85000,
    currency: "XAF",
    features: [
      "3 chambres",
      "Cuisine moderne",
      "2 salles de bain",
      "Parking souterrain",
      "Sécurité 24h/24",
      "Balcon",
    ],
  },
  {
    id: 10,
    name: "Chambre simple - Quartier Savane",
    location: "Savane, Dschang",
    image: "https://images.pexels.com/photos/2635038/pexels-photo-2635038.jpeg",
    isAvailable: true,
    isCertified: false,
    type: "Chambre simple",
    capacity: "1 place",
    price: 15000,
    currency: "XAF",
    features: ["Lit", "Bureau", "Armoire", "Cuisine partagée", "Cour arrière"],
  },
  {
    id: 11,
    name: "Studio avec vue sur la ville",
    location: "Centre-ville, Dschang",
    image: "https://images.pexels.com/photos/1329711/pexels-photo-1329711.jpeg",
    isAvailable: true,
    isCertified: true,
    type: "Studio",
    capacity: "1 place",
    price: 50000,
    currency: "XAF",
    features: [
      "Lit",
      "Cuisine équipée",
      "Salle de bain privée",
      "WiFi",
      "Climatisation",
      "Vue sur la ville",
    ],
  },
  {
    id: 12,
    name: "Chambre spacieuse pour couple",
    location: "Campus A, Dschang",
    image: "https://images.pexels.com/photos/2082087/pexels-photo-2082087.jpeg",
    isAvailable: true,
    isCertified: true,
    type: "Chambre double",
    capacity: "2 places",
    price: 38000,
    currency: "XAF",
    features: [
      "Lit double",
      "Armoire",
      "Salle de bain privée",
      "WiFi",
      "Balcon",
    ],
  },
  {
    id: 13,
    name: "Appartement F4 familial",
    location: "Foutsa, Dschang",
    image: "https://images.pexels.com/photos/1370295/pexels-photo-1370295.jpeg",
    isAvailable: false,
    isCertified: true,
    type: "Appartement F4",
    capacity: "4 places",
    price: 100000,
    currency: "XAF",
    features: [
      "4 chambres",
      "Cuisine équipée",
      "2 salles de bain",
      "Grand salon",
      "Jardin privé",
    ],
  },
  {
    id: 14,
    name: "Chambre simple à M'mouck",
    location: "M'mouck, Dschang",
    image: "https://images.pexels.com/photos/2874404/pexels-photo-2874404.jpeg",
    isAvailable: true,
    isCertified: false,
    type: "Chambre simple",
    capacity: "1 place",
    price: 17000,
    currency: "XAF",
    features: [
      "Lit",
      "Bureau",
      "Placard",
      "Cuisine partagée",
      "Proche des commerces",
    ],
  },
  {
    id: 15,
    name: "Studio Moderne avec terrasse",
    location: "Route de l'Hôpital, Dschang",
    image: "https://images.pexels.com/photos/1579782/pexels-photo-1579782.jpeg",
    isAvailable: true,
    isCertified: true,
    type: "Studio",
    capacity: "1 place",
    price: 40000,
    currency: "XAF",
    features: [
      "Lit",
      "Cuisine équipée",
      "Salle de bain privée",
      "Terrasse",
      "WiFi",
      "Sécurité 24/7",
    ],
  },
  {
    id: 16,
    name: "Chambre en résidence universitaire",
    location: "Campus B, Dschang",
    image:
      "https://images.pexels.com/photos/16654824/pexels-photo-16654824/free-photo-of-empty-bunk-bed-and-desk-in-hostel-room.jpeg",
    isAvailable: true,
    isCertified: false,
    type: "Chambre en colocation",
    capacity: "1 place",
    price: 10000,
    currency: "XAF",
    features: [
      "Lit superposé",
      "Bureau partagé",
      "Salle de bain commune",
      "Cuisine commune",
      "Salle d'étude",
    ],
  },
  {
    id: 17,
    name: "Appartement cosy près de l'IUT",
    location: "IUT, Dschang",
    image: "https://images.pexels.com/photos/2205565/pexels-photo-2205565.jpeg",
    isAvailable: true,
    isCertified: true,
    type: "Appartement F1",
    capacity: "1 place",
    price: 30000,
    currency: "XAF",
    features: [
      "Lit",
      "Cuisine kitchenette",
      "Douche privée",
      "Mobilier moderne",
      "Calme",
    ],
  },
  {
    id: 18,
    name: "Chambre de style loft",
    location: "Centre-ville, Dschang",
    image: "https://images.pexels.com/photos/1699923/pexels-photo-1699923.jpeg",
    isAvailable: false,
    isCertified: true,
    type: "Chambre simple",
    capacity: "1 place",
    price: 28000,
    currency: "XAF",
    features: [
      "Lit surélevé",
      "Espace de travail",
      "Salle de bain privée",
      "WiFi",
      "Décoration moderne",
    ],
  },
  {
    id: 19,
    name: "Maison meublée",
    location: "Savane, Dschang",
    image: "https://images.pexels.com/photos/259972/pexels-photo-259972.jpeg",
    isAvailable: true,
    isCertified: true,
    type: "Maison",
    capacity: "5 places",
    price: 150000,
    currency: "XAF",
    features: [
      "3 chambres",
      "Salon complet",
      "Cuisine équipée",
      "2 salles de bain",
      "Terrasse",
      "Jardin",
    ],
  },
  {
    id: 20,
    name: "Chambre avec accès piscine",
    location: "M'mouck, Dschang",
    image: "https://images.pexels.com/photos/206172/pexels-photo-206172.jpeg",
    isAvailable: true,
    isCertified: false,
    type: "Chambre double",
    capacity: "2 places",
    price: 55000,
    currency: "XAF",
    features: [
      "Lit double",
      "Salle de bain privée",
      "Accès piscine",
      "WiFi",
      "Calme",
    ],
  },
];
